DOC: Point to SurfaceTopography for details on installation
ContactEngineering/ContactMechanics pull request #47
Opened 2021-11-10 12:53 UTC by AntoineSIMTEK

2021-11-10 13:51 UTC, AntoineSIMTEK commented
@pastewka do you know how to strat the test.yml workflow ? I added the file but nothing happens

2021-11-10 15:43 UTC, pastewka approved these changes

2021-11-10 15:46 UTC, pastewka commented
I don't remember. I thought it would run automatically.

2021-11-11 07:40 UTC, AntoineSIMTEK commented
Ok I spotted the error: [MaskedArray.max](https://numpy.org/doc/stable/reference/generated/numpy.ma.MaskedArray.max.html) does not possess that argument. 

However, I thought we wanted to get rid of masked arrays in ContactMechanics simulations.

So the problem will probably solve itself in ContactMechnics.

2021-11-11 13:52 UTC, pastewka commented
I've fixed the max problem in NuMPI - see here: https://github.com/IMTEK-Simulation/NuMPI/pull/56

2021-11-11 14:01 UTC, AntoineSIMTEK commented
Now there is another problem. It seems that Flake8 is crashing ...

2021-11-22 13:10 UTC, pastewka requested changes

2021-11-22 13:10 UTC, pastewka commented on requirements.txt
> +NuMPI>=0.2.0
I think you want 0.3.0 because that fixes the `initial` problem

2021-11-22 19:51 UTC, pastewka approved these changes

2021-11-22 20:23 UTC, merged